from enum import Enum
class ServerReturnMsg(Enum):
    FUNC_SUCCESS = 'FUNC_SUCCESS'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    NO_FREE_SERVER = 'NO_FREE_SERVER'
    SOURCE_INVALID = 'SOURCE_INVALID'
    ENGINE_IS_NONE = 'ENGINE_IS_NONE'
    ENGINE_ACTIVATE_THREAD = 'ENGINE_ACTIVATE_THREAD'
    ENGINE_NOT_ACTIVATE = 'ENGINE_NOT_ACTIVATE'
    ENGINE_SIM_RUNNING = 'ENGINE_SIM_RUNNING'
    ENGINE_USED = 'ENGINE_USED'
    FLAG_ERROR = 'FLAG_ERROR'
    FUNC_PARAM_ERROR = 'FUNC_PARAM_ERROR'
    FUNC_NOT_FOUND = 'FUNC_NOT_FOUND'
    FUNC_IS_NONE = 'FUNC_IS_NONE'
    FUNC_FAILED = 'FUNC_FAILED'
    USER_EMPTY = 'USER_EMPTY'
    USER_INVALID = 'USER_INVALID'
    IP_EMPTY = 'IP_EMPTY'
    INVALID_LARGE_SAMPLE_SCRIPT = 'INVALID_LARGE_SAMPLE_SCRIPT'
    LARGE_SAMPLE_SIM_RUNNING = 'LARGE_SAMPLE_SIM_RUNNING'
    LARGE_SAMPLE_SIM_NOT_RUNNING = 'LARGE_SAMPLE_SIM_NOT_RUNNING'
    TIMEOUT = 'TIMEOUT'

class SimState(Enum):
    """ 仿真引擎的状态 """
    RUNNING = 'RUNNING'
    STOP = 'STOP'

class InvalidScriptName(Enum):
    USER_UPLOAD_SCRIPT = 'USER_UPLOAD_SCRIPT'

class SimMode(Enum):
    ''' 仿真模式 '''
    FREE = 'FREE'   # 自由模式
    SINGLE = 'SINGLE'   # 单一模式
    PARALLEL = 'PARALLEL'   # 并行模式
    BRANCH_DEDUCE = 'BRANCH_DEDUCE' # 分支推演模式
