# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simserver.proto',
  package='simserver',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.examples.simserverB\016SimServerProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsimserver.proto\x12\tsimserver\"Y\n\x06MsgStr\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nbytes_data\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x42\x07\n\x05_dataB\r\n\x0b_bytes_data2<\n\x07Greeter\x12\x31\n\x07\x63ontrol\x12\x11.simserver.MsgStr\x1a\x11.simserver.MsgStr\"\x00\x42\x34\n\x1aio.grpc.examples.simserverB\x0eSimServerProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_MSGSTR = _descriptor.Descriptor(
  name='MsgStr',
  full_name='simserver.MsgStr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='simserver.MsgStr.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='simserver.MsgStr.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes_data', full_name='simserver.MsgStr.bytes_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_data', full_name='simserver.MsgStr._data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bytes_data', full_name='simserver.MsgStr._bytes_data',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=30,
  serialized_end=119,
)

_MSGSTR.oneofs_by_name['_data'].fields.append(
  _MSGSTR.fields_by_name['data'])
_MSGSTR.fields_by_name['data'].containing_oneof = _MSGSTR.oneofs_by_name['_data']
_MSGSTR.oneofs_by_name['_bytes_data'].fields.append(
  _MSGSTR.fields_by_name['bytes_data'])
_MSGSTR.fields_by_name['bytes_data'].containing_oneof = _MSGSTR.oneofs_by_name['_bytes_data']
DESCRIPTOR.message_types_by_name['MsgStr'] = _MSGSTR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgStr = _reflection.GeneratedProtocolMessageType('MsgStr', (_message.Message,), {
  'DESCRIPTOR' : _MSGSTR,
  '__module__' : 'simserver_pb2'
  # @@protoc_insertion_point(class_scope:simserver.MsgStr)
  })
_sym_db.RegisterMessage(MsgStr)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='simserver.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='control',
    full_name='simserver.Greeter.control',
    index=0,
    containing_service=None,
    input_type=_MSGSTR,
    output_type=_MSGSTR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
