# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import simserver_pb2 as simserver__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.control = channel.unary_unary(
                '/simserver.Greeter/control',
                request_serializer=simserver__pb2.MsgStr.SerializeToString,
                response_deserializer=simserver__pb2.MsgStr.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def control(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'control': grpc.unary_unary_rpc_method_handler(
                    servicer.control,
                    request_deserializer=simserver__pb2.MsgStr.FromString,
                    response_serializer=simserver__pb2.MsgStr.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simserver.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simserver.Greeter/control',
            simserver__pb2.MsgStr.SerializeToString,
            simserver__pb2.MsgStr.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
